### ISSUE TITLE
论文代码和前端学习安排

### ISSUE THREAD

**Issue by gx12345618** [LiuDao-C/Vue-MiMall#1]
我是看了您在其他人的github中发表评论我才找到您的，就是这个人的代码“PaulGithubAccount/Paul_EE”，然后我想问的是您的研究方向是什么？我想我们看了同一个代码方向应该很相近吧，然后进了您的github主页还有意外收获，我对前端也比较感兴趣，想知道您学前端的一些经验，学习时间安排，刷题策略以及面试经验，希望您百忙之中能回复我，打扰了，谢谢

**Comment by LiuDao-C** [comment]
你好，你是想问研究生的论文相关还是前端求职相关






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiuDao-C/Vue-MiMall"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月28日(星期一) 下午4:10
收件人:&nbsp;"LiuDao-C/Vue-MiMall"<Vue-MiMall@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LiuDao-C/Vue-MiMall] 论文代码和前端学习安排 (#1)





 
我是看了您在其他人的github中发表评论我才找到您的，就是这个人的代码“PaulGithubAccount/Paul_EE”，然后我想问的是您的研究方向是什么？我想我们看了同一个代码方向应该很相近吧，然后进了您的github主页还有意外收获，我对前端也比较感兴趣，想知道您学前端的一些经验，学习时间安排，刷题策略以及面试经验，希望您百忙之中能回复我，打扰了，谢谢

**Comment by gx12345618** [comment]
其实您有时间我都想请教一下，没有时间就麻烦您回答一下研究生论文相关的问题吧  #！你用这个代码发表的文章可以分享给我吗？
